channels:
- conda-forge

dependencies:
- python=3.10.*

# A linux desktop environment
- websockify

- numpy==1.22.*
- matplotlib==3.5.1

- pip
- pip:
  - jupyter-desktop-server==0.1.3
  - -r infra-requirements.txt
