name: astrods

channels:
- conda-forge

dependencies:
- python=3.9.*

# A linux desktop environment
- websockify

- numpy==1.22.*
- matplotlib==3.5.*
- graphviz>=2.50.0
- psycopg2==2.9.*
- pytorch>=1.10.0
- pytorch-lightning

- pip

- pip:
  - jupyter-desktop-server==0.1.3
  - -r infra-requirements.txt
  - tensorflow>=2.7.*
  - opencv-python>=4.5.5.62
  - nose2>=0.10.0
  - sympy
  - scipy
  - scikit-learn==1.0.*
  - scikit-image==0.19.*
  - beautifulsoup4
  - tqdm
  - h5py
  - netcdf4
  - numexpr
  - corner==2.2.*
  - dask>=2021.12.0
  - dask-ml>=2021.11.30
  - distributed>=2021.12.0
  - jaxlib>=0.1.75
  - SQLAlchemy>=1.4.29
  - xarray>=0.20.2
  - nltk>=3.6.7
  - seaborn>=0.11.2
  - bqplot>=0.12.31
  - astroquery>=0.4.5
  - astropy>=5.0
  - dustmaps>=1.0.9
  - pyvo>=1.2
  - joblib>=1.1.0
  - aesara>=2.3.4
  - pymc3>=3.11.4
  - requests>=2.27.1
  - ipycanvas
  - altair>=4.2.0
  - pytz>=2021.3
  - keras==2.7.*
  - keras-preprocessing==1.1.*
  - lightkurve
  - ipyparallel>=8.1.0
  - jupyter-tensorboard>=0.2.0